development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: test
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: rails4_example_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1

production:
  clients:
    default:
      database: <%= ENV['MONGODB_DB'] %>
      hosts:
        - <%="#{ENV['MONGODB_DB_HOST']}:#{ENV['MONGODB_DB_PORT']}" %>
      options:
        user: <%= ENV['MONGODB_DB_USERNAME'] %>
        password: <%= ENV['MONGODB_DB_PASSWORD'] %>
